version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myChangeStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i0af4zca85cx"
s3_prefix = "myChangeStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=287789953770.dkr.ecr.us-east-1.amazonaws.com/mycloudformationf8d10587/helloworldfunction19d43fc4repo"]
